import random
n1 = random.randint(1, 10)
print('O sucessor do nº {} é {} e o seu antecessor é {}'.format(n1, n1+1, n1-1))
print('O dobro de {} é {}, o triplo é {} e a raiz quadrada é {}'.format(n1, n1*2, n1*3, n1**2))
n2 = int(input('Outro número inteiro: '))
print('A média de {} e {} é {:.2f}'.format(n1, n2, (n1+n2)/2))
m1 = int(input('Uma metragem inteira: '))
print('{}m em centímetros é {}cm e milímetros é {}mm'.format(m1, m1*100, m1*1000))
print('Vamos fazer a tabuada do primeiro número que você digitou:')
print('{} x 0 = {}'.format(n1, n1*0))
print('{} x 1 = {}'.format(n1, n1*1))
print('{} x 2 = {}'.format(n1, n1*2))
print('{} x 3 = {}'.format(n1, n1*3))
print('{} x 4 = {}'.format(n1, n1*4))
print('{} x 5 = {}'.format(n1, n1*5))
print('{} x 6 = {}'.format(n1, n1*6))
print('{} x 7 = {}'.format(n1, n1*7))
print('{} x 8 = {}'.format(n1, n1*8))
print('{} x 9 = {}'.format(n1, n1*9))
print('{} x 10 = {}'.format(n1, n1*10))